defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

port = ":80"
graceTimeOut = 10
logLevel = "DEBUG"

[web]
address = ":81"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.dev"
watch=true
